import BigNumber from 'bignumber.js';
declare const GWEI = 1000000000;
declare const DEFAULT_TIMEOUT = 10000;
declare const ROUND_UP = 1;
declare const ROUND_DOWN = 2;
declare const GWEI_PRECISION = 9;
declare const INT_PRECISION = 0;
declare const SUCCESS_STATUS = 200;
declare const BG_ZERO: BigNumber;
declare const PERCENT_MULTIPLIER = 100;
export { GWEI, DEFAULT_TIMEOUT, ROUND_UP, ROUND_DOWN, GWEI_PRECISION, INT_PRECISION, SUCCESS_STATUS, BG_ZERO, PERCENT_MULTIPLIER };
