import { EstimatedGasPrice } from './types';
declare const FEE_HISTORY_BLOCKS = 10;
declare const FEE_HISTORY_PERCENTILE = 5;
declare const DEFAULT_BASE_FEE = 20;
declare const DEFAULT_PRIORITY_FEE = 3;
declare const PRIORITY_FEE_INCREASE_BOUNDARY = 200;
declare const FALLBACK_ESTIMATE: EstimatedGasPrice;
export { DEFAULT_BASE_FEE, FALLBACK_ESTIMATE, FEE_HISTORY_BLOCKS, DEFAULT_PRIORITY_FEE, FEE_HISTORY_PERCENTILE, PRIORITY_FEE_INCREASE_BOUNDARY, };
