import BigNumber from 'bignumber.js'

const GWEI = 1e9
const DEFAULT_TIMEOUT = 10000

const ROUND_UP = 1
const ROUND_DOWN = 2
const GWEI_PRECISION = 9
const INT_PRECISION = 0

const SUCCESS_STATUS = 200
const BG_ZERO = new BigNumber(0)
const PERCENT_MULTIPLIER = 100
const DEFAULT_BLOCK_DURATION = 10

export {
  GWEI,
  DEFAULT_TIMEOUT,
  ROUND_UP,
  ROUND_DOWN,
  GWEI_PRECISION,
  INT_PRECISION,
  SUCCESS_STATUS,
  BG_ZERO,
  PERCENT_MULTIPLIER,
  DEFAULT_BLOCK_DURATION,
}
